### ISSUE TITLE
Are meme-based status codes needed?

### ISSUE THREAD

**Issue by eimantas** [joho/7XX-rfc#37]
Memes are changing way too fast (considering the big picture) and I don't think we should engrave them into any of the status codes. I believe that technological, management and culture-based (memeless) status codes are enough. Yes, I understand that this clashes with my proposal regarding f7u12 to reddit-based status codes, hence I retract it .)

**Comment by joho** [comment]
No, you're totally correct. #185 will address this with a new section.

**Comment by cmckni3** [comment]
I actually like the meme status codes

**Comment by extensibleseth** [comment]
I would like to make a case for memes from a historical perspective. I.e.: HTTP 7XX Killroy was here. The mark they leave on culture is indelible even if their origins are lost.

**Comment by joho** [comment]
I agree that meme have made an indelible mark on our culture, but in the six years since I started this repo I've come to realise that the vocabulary of silicon valley disrupting meritocratic newspeak has made a far more indelible mark.

As such, I'm taking the opportunity of the format change to re-prioritise the themes, which I'll fill in over the coming month.

This is fixed by #185

**Comment by extensibleseth** [comment]
I'll be honest, I just want Confounded by Ponies.
